Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.provision "shell" , path: "script.sh"
	config.vm.network "forwarded_port" , guest: 80 , host: 8080 
	config.vm.synced_folder "./www_1" , "/var/www/html/"
end
